global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Backend API (custom metrics path)
  - job_name: 'backend-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['backend-api:8000']
    scrape_interval: 30s

  # Frontend (check /metrics returns valid Prometheus format)
  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s

  # Healthcheck service
  - job_name: 'healthcheck'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['healthcheck:5000']
    scrape_interval: 15s

  # Project bridge
  - job_name: 'project-bridge'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['project-bridge:5001']
    scrape_interval: 30s

  # Postgres Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Docker daemon metrics (host only valid on Linux/Mac with Docker socket exposed)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # Blackbox exporter
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://frontend:80
          - http://backend-api:8000/api/health
          - https://jylmqyrs.manus.space
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
